### ISSUE TITLE
TFT

### ISSUE THREAD

**Issue by Egocentrism** [SaffatHasan/AutoQr#35]
Can u add Mode TFT normal/ranked ?

**Comment by SaffatHasan** [comment]
I won't support this feature (I don't play TFT), but you can just make a copy of #36 and add TFT queue modes.

```json
  {
    "queueId": 1090,
    "map": "Convergence",
    "description": "Teamfight Tactics games",
    "notes": null
  },
  {
    "queueId": 1100,
    "map": "Convergence",
    "description": "Ranked Teamfight Tactics games",
    "notes": null
  },
```

**Comment by SaffatHasan** [comment]
You may also find this repo interesting: https://github.com/KebsCS/KBotExt

**Comment by Egocentrism** [comment]
I'm very stupid and don't understand how to set everything up, could you explain in more detail?
